# Generated by Django 4.2.28 on 2026-02-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='hidden_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
