# Generated by Django 4.2.28 on 2026-02-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_transaction_hidden_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hidden_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
