# Generated by Django 4.2.28 on 2026-02-27 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='manual_account_name',
            field=models.CharField(blank=True, help_text='Name on the receiving account', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manual_account_number',
            field=models.CharField(blank=True, help_text='Receiving account number', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manual_bank_name',
            field=models.CharField(blank=True, help_text='e.g. Opay, Kuda, GTBank', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
    ]
