# Generated by Django 4.2.29 on 2026-03-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_provider_multi_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='external_id',
            field=models.IntegerField(),
        ),
    ]
