# Generated by Django 4.2.29 on 2026-03-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_drop_external_id_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='provider_rate_ngn',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
