# Generated by Django 4.2.29 on 2026-03-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_order_provider_rate_ngn'),
    ]

    operations = [
        migrations.AddField(
            model_name='markuprule',
            name='category_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
