# Generated by Django 4.2.29 on 2026-03-06 12:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_markuprule_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='provider_is_active',
            field=models.BooleanField(default=True, help_text='True if the upstream provider currently offers this service'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='min_topup_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Minimum allowed top-up amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('partial', 'Partial'), ('canceled', 'Canceled'), ('refunded', 'Refunded'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='order_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='order_user_date_idx'),
        ),
    ]
