# Generated by Django 4.2.29 on 2026-03-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_provider_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopupCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional text content for the card')),
                ('image', models.ImageField(blank=True, help_text='Square image works best (1:1 ratio)', null=True, upload_to='popups/')),
                ('action_url', models.URLField(blank=True, help_text='Optional link when card is clicked', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Popup Card',
                'verbose_name_plural': 'Popup Cards',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
