# Generated by Django 4.2.29 on 2026-03-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_popupcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popupcard',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
