# Generated by Django 4.2.29 on 2026-03-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_popupcard_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupcard',
            name='action_text',
            field=models.CharField(blank=True, default='Learn More', help_text="Text to display on the action button (e.g., 'Learn More', 'Buy Now')", max_length=50),
        ),
    ]
