# Generated by Django 4.2.29 on 2026-04-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_payment_method_toggles'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reseller_order_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Auto-assigned sequential integer ID for SMM Panel API v2 reseller compatibility', null=True, unique=True),
        ),
    ]
