# Generated by Django 4.2.29 on 2026-04-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_reseller_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('web', 'Web'), ('api', 'API')], db_index=True, default='web', help_text='web = placed via dashboard, api = placed via reseller API key', max_length=10),
        ),
    ]
