# Generated by Django 4.2.29 on 2026-09-03 13:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_admin_notifications_and_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAuthor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(default='Editor In Chief', max_length=150)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('bio', models.TextField(blank=True)),
                ('social_x', models.URLField(blank=True, max_length=300, null=True)),
                ('social_linkedin', models.URLField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blog Author',
                'verbose_name_plural': 'Blog Authors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=350, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Short summary for search snippets and cards')),
                ('content', models.TextField(help_text='Full HTML/Markdown formatted content')),
                ('featured_image', models.URLField(blank=True, help_text='Cloudinary CDN or asset URL', max_length=500, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], db_index=True, default='PUBLISHED', max_length=20)),
                ('featured', models.BooleanField(default=False, help_text='Feature on blog hero / homepage')),
                ('read_time', models.CharField(default='5 min read', max_length=50)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo_title', models.CharField(blank=True, help_text='Custom <title> tag override', max_length=300)),
                ('seo_description', models.TextField(blank=True, help_text='Custom <meta description> tag override')),
                ('canonical_url', models.URLField(blank=True, help_text='Custom canonical link', max_length=500, null=True)),
                ('focus_keyword', models.CharField(blank=True, max_length=150)),
                ('faqs', models.JSONField(blank=True, default=list, help_text="List of {q: '...', a: '...'} for Schema.org FAQPage")),
                ('cta_title', models.CharField(blank=True, default='Boost Your Social Media Accounts Now!', max_length=255)),
                ('cta_description', models.TextField(blank=True, default="It's fun and easy. Just choose the amount of followers, likes, or views that suits your needs, and blast off to insane account growth.")),
                ('cta_button_text', models.CharField(blank=True, default='Get Boosting Now!', max_length=100)),
                ('cta_url', models.CharField(blank=True, default='/register', max_length=300)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.blogauthor')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.blogcategory')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
