# Generated by Django 4.2.29 on 2026-09-12 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_otporder_rental_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adminauditlog',
            new_name='core_admina_action_0bd741_idx',
            old_name='core_adminau_action_7eb943_idx',
        ),
        migrations.RenameIndex(
            model_name='adminauditlog',
            new_name='core_admina_actor_i_de0819_idx',
            old_name='core_adminau_actor_i_5df3a2_idx',
        ),
        migrations.RenameIndex(
            model_name='adminauditlog',
            new_name='core_admina_target__c70c49_idx',
            old_name='core_adminau_target__c74c61_idx',
        ),
        migrations.RenameIndex(
            model_name='otporder',
            new_name='core_otpord_user_id_d0f3c5_idx',
            old_name='core_otpord_user_id_44f1c9_idx',
        ),
        migrations.RenameIndex(
            model_name='otporder',
            new_name='core_otpord_status_2fbe95_idx',
            old_name='core_otpord_status_67a2bd_idx',
        ),
        migrations.RenameIndex(
            model_name='usersession',
            new_name='core_userse_user_id_c33865_idx',
            old_name='core_userses_user_id_9cf0a1_idx',
        ),
        migrations.RenameIndex(
            model_name='usersession',
            new_name='core_userse_session_1ee7ed_idx',
            old_name='core_userses_session_1a4b82_idx',
        ),
    ]
